const auth = require('../auth')
const express = require('express')
const Top5ListController = require('../controllers/top5list-controller')
const UserController = require('../controllers/user-controller')
const CommentController = require('../controllers/comment-controller')
const router = express.Router()

router.post('/top5list', auth.verify, Top5ListController.createTop5List)
router.put('/top5list/:id', auth.verify, Top5ListController.updateTop5List)
router.put('/top5listunimportant/:id', Top5ListController.updateUnimportantTop5List)
router.delete('/top5list/:id', auth.verify, Top5ListController.deleteTop5List)
router.get('/top5list/:id', Top5ListController.getTop5ListById)
router.get('/top5lists', Top5ListController.getTop5Lists)
router.get('/top5listpairs', auth.verify, Top5ListController.getTop5ListPairs)

router.post('/register', UserController.registerUser)
router.get('/loggedIn', UserController.getLoggedIn)
router.get('/logout', UserController.logoutUser)
router.post('/login', UserController.loginUser)

router.post('/top5listcomment', auth.verify, CommentController.createTop5ListComment)
router.post('/top5listcommunity', auth.verify, Top5ListController.updateCommunityTop5List)
router.post('/top5listdeletecommunity', auth.verify, Top5ListController.deleteCommunityTop5List)
router.get('/top5listcommunity', Top5ListController.getCommunityTop5List)
module.exports = router